apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-graviton
spec:
  replicas: 5
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "3600"]
      tolerations:
        - key: "graviton"
          operator: "Equal"
          value: "enabled"
          effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/arch: arm64
