apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
spec:
  chart:
    spec:
      chart: karpenter
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
  interval: 5m
  test:
    enable: false
  values:
    replicas: 1
    settings:
      clusterName: eks-dev-eu-west-1
      clusterEndpoint: "https://xxxxxxxxxxxxxx.eu-west-1.eks.amazonaws.com"
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
