apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karpenter
resources:
  - ../base
  - np-graviton.yaml
  - np-x86.yaml
patches:
  - target:
      kind: HelmRelease
      name: karpenter
    path: helmrelease.yaml
