apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  kubelet:
    maxPods: 110
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 120Gi
        volumeType: gp3
        deleteOnTermination: true
  amiSelectorTerms:
    - id: ami-0b35f753d8efc4687
  role: "KarpenterNodeRole-eks-dev-eu-west-1"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-dev-eu-west-1"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-dev-eu-west-1"
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: [ "amd64" ]
        - key: kubernetes.io/os
          operator: In
          values: [ "linux" ]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: [ "m5", "c5", "r5", "m6i", "c6i", "r6i" ]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: Never
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
